Repository alexthompson207/rancid-tomatillos, pull requests merged in 2021-04, with the labels that each got.

#24 Feature/testing part 1
  cypress.json
  cypress/fixtures/example.json
  cypress/fixtures/movies.js
  cypress/integration/all-movies-spec.js
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: User Stories, enhancement, testing

#25 Feature/movie info tests
  cypress/fixtures/movie-info.js
  cypress/fixtures/movie-video.js
  cypress/fixtures/movies.js
  cypress/integration/all-movies-spec.js
  cypress/integration/movie-info-spec.js
  package.json
Labels: testing

#26 Fix/refactor api
  cypress/integration/all-movies-spec.js
  cypress/integration/movie-info-spec.js
  src/App.js
  src/Error/Error.js
  src/MovieInfo/MovieInfo.js
  src/apiCalls.js
Labels: testing

#27 Feature/prop types
  package-lock.json
  package.json
  src/App.js
  src/Error/Error.js
  src/MovieCard/MovieCard.js
  src/MovieInfo/MovieInfo.js
  src/MoviesView/MoviesView.js
  src/Search-Bar/Search-Bar.css
  src/Search-Bar/Search-Bar.js
  src/apiCalls.js
Labels: enhancement

#28 Feature/form search
  src/App.js
  src/MovieCard/MovieCard.js
  src/MoviesView/MoviesView.css
  src/MoviesView/MoviesView.js
  src/Search-Bar/Search-Bar.css
  src/Search-Bar/Search-Bar.js
  src/images/blood.svg
  src/images/tomato-bad.svg
  src/index.css
Labels: User Stories, enhancement

#30 Fix/refactor project files
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  public/favicon.ico
  public/favicon.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/.App.js.swp
  src/App.test.js
  src/App/App.css
  src/App/App.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: Chores
